// languages.js
const languages = [
    // Top 20 Global
    {name: "English", code: "en-US"},
    {name: "Mandarin", code: "zh-CN"},
    {name: "Spanish", code: "es-ES"},
    {name: "French", code: "fr-FR"},
    {name: "Arabic", code: "ar-SA"},
    {name: "Bengali", code: "bn-BD"},
    {name: "Portuguese", code: "pt-PT"},
    {name: "Russian", code: "ru-RU"},
    {name: "Japanese", code: "ja-JP"},
    {name: "Punjabi", code: "pa-IN"},
    {name: "German", code: "de-DE"},
    {name: "Javanese", code: "jv-ID"},
    {name: "Wu Chinese", code: "wuu-CN"},
    {name: "Telugu", code: "te-IN"},
    {name: "Vietnamese", code: "vi-VN"},
    {name: "Korean", code: "ko-KR"},
    {name: "Marathi", code: "mr-IN"},
    {name: "Tamil", code: "ta-IN"},
    {name: "Turkish", code: "tr-TR"},
    {name: "Italian", code: "it-IT"},

    // Top 10 Indian
    {name: "Hindi", code: "hi-IN"},
    {name: "Gujarati", code: "gu-IN"},
    {name: "Malayalam", code: "ml-IN"},
    {name: "Kannada", code: "kn-IN"},
    {name: "Odia", code: "or-IN"},
    {name: "Assamese", code: "as-IN"},
    {name: "Marathi", code: "mr-IN"},
    {name: "Punjabi", code: "pa-IN"},
    {name: "Telugu", code: "te-IN"},
    {name: "Bengali", code: "bn-BD"},

    // Remaining 30 sample / popular languages
    {name: "Swahili", code: "sw-KE"},
    {name: "Urdu", code: "ur-PK"},
    {name: "Farsi", code: "fa-IR"},
    {name: "Thai", code: "th-TH"},
    {name: "Hebrew", code: "he-IL"},
    {name: "Greek", code: "el-GR"},
    {name: "Dutch", code: "nl-NL"},
    {name: "Polish", code: "pl-PL"},
    {name: "Czech", code: "cs-CZ"},
    {name: "Hungarian", code: "hu-HU"},
    {name: "Finnish", code: "fi-FI"},
    {name: "Norwegian", code: "no-NO"},
    {name: "Danish", code: "da-DK"},
    {name: "Swedish", code: "sv-SE"},
    {name: "Indonesian", code: "id-ID"},
    {name: "Filipino", code: "fil-PH"},
    {name: "Malay", code: "ms-MY"},
    {name: "Burmese", code: "my-MM"},
    {name: "Khmer", code: "km-KH"},
    {name: "Lao", code: "lo-LA"},
    {name: "Ukrainian", code: "uk-UA"},
    {name: "Serbian", code: "sr-RS"},
    {name: "Croatian", code: "hr-HR"},
    {name: "Slovak", code: "sk-SK"},
    {name: "Bulgarian", code: "bg-BG"},
    {name: "Romanian", code: "ro-RO"},
    {name: "Mongolian", code: "mn-MN"},
    {name: "Hindi-Latin", code: "hi-Latn"},
    {name: "Tamil-Latin", code: "ta-Latn"},
    {name: "Bengali-Latin", code: "bn-Latn"}
];
